setwd('C:/Users/tobij/Desktop/Ipynb Tasks/Giredestrant')
controls <- read.csv('controls.csv', row.names=1)
head(controls)
sample_names <- colnames(controls)
conditions <- c(rep('dmso', 4), rep('giredestrant', 4)) 
conditions <- as.factor(conditions)
column_data <- data.frame(row.names=sample_names, condition=conditions)
library(DESeq2)
dds <- DESeqDataSetFromMatrix(countData=controls, colData=column_data, design=~condition)
dds <- DESeq(dds)
res <- results(dds)
summary(res)
write.csv(as.data.frame(res), 'results.csv')