setwd('C:/Users/tobij/Desktop/Ipynb Tasks/Giredestrant')
controls <- read.csv('gpx4s.csv', row.names=1)
head(controls)
sample_names <- colnames(controls)
conditions <- c(rep('d_gpx4', 4), rep('g_gpx4', 4)) 
conditions <- as.factor(conditions)
column_data <- data.frame(row.names=sample_names, condition=conditions)
library(DESeq2)
dds <- DESeqDataSetFromMatrix(countData=controls, colData=column_data, design=~condition)
dds <- DESeq(dds)
res <- results(dds)
summary(res)
write.csv(as.data.frame(res), 'results.csv')
cleaned_res <- na.omit(res)
write.csv(as.data.frame(cleaned_res), 'cleaned_gpx4s_results.csv')